### PR TITLE
refactor: split dlt_common and dlt_log

### PR DESCRIPTION
**Pull request by danielweber2018**
Seperate all internal logging function into an own source file. This reduces the scope of the sprawling dlt_common source file.

The program was tested solely for our own use cases, which might differ from yours.
Licensed under Mozilla Public License Version 2.0

<sup>Daniel Weber, [daniel.w.weber@mercedes-benz.com](mailto:daniel.w.weber@mercedes-benz.com), Mercedes-Benz Technology Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

### CODE REVIEW

**Comment by danielweber2018** [comment]
@michael-methner Here my refactor PR like discussed at [https://github.com/COVESA/dlt-daemon/pull/369#discussion_r1095824332](url)

**Comment by minminlittleshrimp** [comment]
Hello @michael-methner 
This refactor is good, however I think it needs carefully reviewing from DLT team and considering upscale to be  new release.

**Comment by danielweber2018** [comment]
Hello @michael-methner ,
this MR has been open for 6 months today. I know it's a big change, and you probably have little time.
Nevertheless, I would greatly appreciate a review or another reaction.

Thank you in advance!

**Comment by danielweber2018** [comment]
Hello @michael-methner ,
this PR is now over one year old. Some things are now outdated and I have also found some mistakes/conflicts in the code.
If you would like to review this PR, please let me know so I can update the PR.
If I don't hear from you, I'll assume there won't be a review and therefore won't invest the time in maintaining this PR.
If this PR is thematically undesirable, you can also close it.

**Comment by michael-methner** [comment]
Hello @danielweber2018 ,

thanks for your patience. I had a quick glance at the commit and I think is fine and a desirable change. I think it's good to spent some efforts on refactoring to keep the DLT code maintainable.

So please go ahead with your planned rework. I will then review it. I guess reviewing it is not that much of an effort as it is mainly moving code and and not modifying the logic of it.

**Comment by danielweber2018** [comment]
Hello @michael-methner ,
thank you very much for the reponse, I really appreciate it :)
In this case, I will update this PR soon and then get back to you.

**Comment by danielweber2018** [comment]
Hello @michael-methner and @minminlittleshrimp ,
i updated and maintained my PR. I compared the moved code with the current master. So the PR is ready for review and i would be very happy about a soon response.

**Comment by minminlittleshrimp** [comment]
Seems to have merge conflict, let me take sometimes to fix

**Comment by minminlittleshrimp** [comment]
Hello @danielweber2018 
Could you do the merge conflict resolving base on this https://github.com/COVESA/dlt-daemon/pull/654?
Then I can process with merging this PR.
Thanks

**Comment by minminlittleshrimp** [comment]
No response from contributor, create new one & set this to duplicated. Close and continue on: https://github.com/COVESA/dlt-daemon/pull/657

**Pull request closed without merging**
