### PR TITLE
Summary : Fix for Resource and Memory Leak

### PR DESCRIPTION
**Pull request by Manojcv55**
dlt_daemon_client.c Adding NULL check for tok
dlt_daemon_offline_logstorage.c : Adding NULL check for application
dlt_daemon_common.c : fix printf format %d to %ld that formats a long
dlt_common.c: fix printf format %d to %ld that formats a long
dlt_user.c : Fix for Memory Leak
dlt-daemon.c : Fix for Resource Leak
dlt_offline_trace.c : Fix for Resource Leak

Signed-off-by: Mvaradaraj2 <manoj.varadaraj2@harman.com>

### CODE REVIEW

**Comment by ssugiura** [comment]
@Manojcv55 Would you like to provide an update?

**Comment by ssugiura** [comment]
@Manojcv55 Friendly reminder.

**Comment by ssugiura** [comment]
@Manojcv55  Friendly reminder to update PR. Thanks in advance.

**Comment by michael-methner** [comment]
Replaced by https://github.com/COVESA/dlt-daemon/pull/418

**Pull request closed without merging**
