### PR TITLE
Fix atomic build on riscv64

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
Add check for atomic need (e.g. this fixes the build on riscv64 architecture)

### CODE REVIEW

**Comment by michael-methner** [comment]
Hello @LocutusOfBorg ,
thank you for providing the fix and documenting the license correctly.
But I rather do not pull in this commit as DLT is licensed under MPL license and I do not want to contaminate it with other licenses.

Which compilers do require this check? std::atomic is part of C++11, so actually a quite old feature.

**Comment by LocutusOfBorg** [comment]
Its riscv64 architecture, some atomic are not optimizable.
Changing atomic<bool> to atomic<int> works in avoiding the whole -latomic linkage.

**Comment by LocutusOfBorg** [comment]
Hello, this is fixed in a better way from 2224cddf140c060d92455ad3ee585e3abfc38eb2

**Comment by michael-methner** [comment]
> Hello, this is fixed in a better way from [2224cdd](https://github.com/COVESA/dlt-daemon/commit/2224cddf140c060d92455ad3ee585e3abfc38eb2)

Do I understand you correctly, that the linked patch is also solving your issues on riscv64? Then I would close this PR.

**Comment by LocutusOfBorg** [comment]
yes thanks!

**Pull request closed without merging**
